### ISSUE TITLE
/map uses different navbar from rest of the routes

### ISSUE THREAD

**Issue by pjflux2001** [pjflux2001/CareQuest#5]
if you don't want to fix this just ensure that both navbars are less or more the same

**Comment by barthwalumang** [comment]
please attach the picture of the issue. @pjflux2001

**Comment by pjflux2001** [comment]
if you change the current navbar in header.ejs file it wouldn't affect the one present in /map. P.S. - Don't fix it just keep this point in mind so during final deploy we don't mess up the navbars
