### ISSUE TITLE
Some navbar items don't behave same on selection

### ISSUE THREAD

**Issue by pjflux2001** [pjflux2001/CareQuest#6]
![image](https://user-images.githubusercontent.com/46859995/88833100-60d23800-d1ef-11ea-9885-211956398f23.png)
how it should actually work ^^ 

![image](https://user-images.githubusercontent.com/46859995/88833133-6f205400-d1ef-11ea-863d-18144777ec74.png)
how it is working ^^

Fix needed

**Comment by barthwalumang** [comment]
resolved
